version: 0.2  
phases:  
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt -t .
      - aws cloudformation package --template-file template.yml --s3-bucket lambda-deployement-pipeline-bucket-1 --output-template-file lambda_function.yaml   
artifacts:  
  files:
    - lambda_function.yaml
    - template.yml